wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716318115.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.18
      5: 0.16.6
      8:
      - 1
      - 5
      13: darwin-x86_64
